include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/_deployment.yml'

.deploy-backup-db-stage: &deploy-backup-db-stage
  stage: deploy-backup-db

.deploy-backup-db:
  variables: &deploy-backup-db-variables
    DEPLOY_DIR_NAME: deploy_backup-db
    BACKUP_DB_REPOSITORY_URL: https://gitlab.com/redmic-project/postgres/backup-db
    BACKUP_DB_REPOSITORY_BRANCH: dev
    BACKUP_DB_DEPLOY_FILES: .env docker-compose.tmpl.yml docker-compose.dev.yml docker-compose.prod.yml

.deploy-backup-db-before_script: &deploy-backup-db-before_script
  before_script:
    - >
      mkdir -p ${DEPLOY_DIR_NAME};
      cd ${DEPLOY_DIR_NAME};
      urlBase="${BACKUP_DB_REPOSITORY_URL}/-/raw/${BACKUP_DB_REPOSITORY_BRANCH}/deploy";
      for deployFile in ${BACKUP_DB_DEPLOY_FILES};
      do
        wget -q "$${urlBase})/$${deployFile}";
      done;
      cd -;

.deploy-backup-db-development:
  extends: .deploy-development
  <<: *deploy-backup-db-stage
  variables:
    <<: *deploy-backup-db-variables
  <<: *deploy-backup-db-before_script
  environment:
    name: dev/backup-db

.deploy-backup-db-production:
  extends: .deploy-production
  <<: *deploy-backup-db-stage
  variables:
    <<: *deploy-backup-db-variables
  <<: *deploy-backup-db-before_script
  environment:
    name: pro/backup-db

.deploy-backup-db-branch-base:
  variables: &deploy-backup-db-branch-base-variables
    DD_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}
    DD_IMAGE_TAG: ${CI_COMMIT_SHA}

.deploy-backup-db-support-branch: &deploy-backup-db-support-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == "master"
      when: never
    - if: $CI_COMMIT_BRANCH
      when: manual
      allow_failure: true

deploy-backup-db-support-branch-development:
  extends: .deploy-backup-db-development
  variables:
    <<: *deploy-backup-db-branch-base-variables
  <<: *deploy-backup-db-support-branch

.deploy-backup-db-stable-branch: &deploy-backup-db-stable-branch
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
      allow_failure: true

deploy-backup-db-stable-branch-development:
  extends: .deploy-backup-db-development
  variables:
    <<: *deploy-backup-db-branch-base-variables
  <<: *deploy-backup-db-stable-branch

deploy-backup-db-stable-branch-production:
  extends: .deploy-backup-db-production
  variables:
    <<: *deploy-backup-db-branch-base-variables
  <<: *deploy-backup-db-stable-branch

.deploy-backup-db-tag-base:
  variables: &deploy-backup-db-tag-base-variables
    DD_IMAGE_NAME: ${CI_REGISTRY_IMAGE}
    DD_IMAGE_TAG: ${CI_COMMIT_TAG}

.deploy-backup-db-tag: &deploy-backup-db-tag
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true

deploy-backup-db-tag-development:
  extends: .deploy-backup-db-development
  variables:
    <<: *deploy-backup-db-tag-base-variables
  <<: *deploy-backup-db-tag

deploy-backup-db-tag-production:
  extends: .deploy-backup-db-production
  variables:
    <<: *deploy-backup-db-tag-base-variables
  <<: *deploy-backup-db-tag
