version: '3.9'

services:
  backup-files:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/maintenance/backup-files}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        ALPINE_IMAGE_TAG:
        CURL_VERSION:
        BASH_VERSION:
        GLIBC_VERSION:
        AWS_CLI_VERSION:
        BACKUP_PATH:
    environment:
      BACKUP_PATH:
      WORK_PATH:
      AWS_DEFAULT_REGION:
      AWS_OUTPUT:
      PUSHGATEWAY_HOST:
